


name: Python warp

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 0,12 * * *'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ipaddress
        
    - name: Run script
      run: python warp.py
       
    - name: Commit and push changes
      run: |          
          git config --global user.email "3yed1361@gmail.com"
          git config --global user.name "3yed-61"
          git config credential.helper store
          git add -A
          git commit -m "⏳ Automatic update - $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M')"
          git push
